[package]
name = "openmct-pico-pilot-source"
version = "0.1.0"
authors = ["Zachary Kohnen <14093962+DusterTheFirst@users.noreply.github.com>"]
edition = "2018"

[dependencies]
log = { version = "1.0", package = "kv-log-macro" }
serialport = "4.0"
phf = { version = "0.8", features = ["macros"] }
color-eyre = "0.5"
tide = "0.16"
async-std = { version = "1.9", features = ["attributes"] }
serde = { version = "1.0", features = ["derive"] }
femme = "2.1.1"

[patch.crates-io]
async-attributes = { path = "../async-attributes" }
